"use client"
import localFont from "next/font/local";
import "./globals.css";
import Leftside from "../components/leftcomp/Leftside";
import Rightside from "../components/rightcomp/Rightside";
import Navbar from "@/components/Navbar";
import Footer from "@/components/footer/Footer";
import React,{useState , useEffect} from "react";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [isrightvisible , setisrightvisible] = useState(true);
  const [isleftvisible , setisleftvisible] = useState(true);
    
    useEffect(()=>{
     const hanldeResize = ()=>{
       setisrightvisible(window.innerWidth >= 1280)
       setisleftvisible(window.innerWidth >=768)
       }
       hanldeResize();
       window.addEventListener('resize', hanldeResize);
       return ()=>{
        window.removeEventListener('resize', hanldeResize)
       }
    },[])

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       
        <Navbar />
        <div className={` max-w-screen  grid 
          ${isleftvisible ? 'grid-cols-[300px_1fr]' : 'grid-cols-[6fr]' } 
          ${isrightvisible ? ' grid-cols-[300px_1fr_330px]' : ' grid-cols-[300px_1fr]' } ` }>
          <div className="  overflow-auto h-screen sticky hidden md:block  top-0 mt-12">
             <Leftside />
          </div>

          <div className="    bg-white   px-9  ">
            {children}
          </div>
          <div className="  sticky top-0  mt-12 h-screen hidden xl:block  "> <Rightside />
          </div>
        </div>

          

        <div >
          <Footer />
        </div>
        
      </body>
    </html>
  );
}
